/*
 * generated by Xtext
 */
package de.itemis.tooling.asp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ASPUiModule extends de.itemis.tooling.asp.ui.AbstractASPUiModule {
	public ASPUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
