/*
* generated by Xtext
*/
package de.itemis.tooling.asp.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AspOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
