/*
* generated by Xtext
*/
package de.itemis.tooling.asp.ui.contentassist;

import de.itemis.tooling.asp.ui.contentassist.AbstractASPProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ASPProposalProvider extends AbstractASPProposalProvider {

}
