/*
 * generated by Xtext
 */
package de.itemis.tooling.asp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ASPRuntimeModule extends de.itemis.tooling.asp.AbstractASPRuntimeModule {

}
